package io.github.parkkevinsb.flower.agent.runtime;

public enum AuditEventType {
    ACTION_PROPOSED,
    ACTION_RESOLVED,
    VALIDATION_COMPLETED,
    POLICY_EVALUATED,
    DRY_RUN_COMPLETED,
    APPROVAL_REQUESTED,
    APPROVAL_APPROVED,
    APPROVAL_REJECTED,
    ACTION_EXECUTION_STARTED,
    ACTION_EXECUTION_COMPLETED,
    ACTION_EXECUTION_FAILED,
    ACTION_RUNTIME_FAILED,
    ACTION_DENIED,
    ACTION_DUPLICATE
}
